export default {
  ROUTE_CHANGE: 'ROUTE_CHANGE',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  LEFT_SIDE: 'LEFT_SIDE',
  TOGGLE_LEFT_SIDE: 'TOGGLE_LEFT_SIDE',
  SET_CURRENT_PAGE_META: 'SET_CURRENT_PAGE_META'
}
