export default {
  ROUTE_CHANGE: 'ROUTE_CHANGE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LEFT_SIDE: 'LEFT_SIDE',
  TOGGLE_LEFT_SIDE: 'TOGGLE_LEFT_SIDE',
  SET_CURRENT_PAGE_META: 'SET_CURRENT_PAGE_META',
  REFRESH_LOGIN_STATE: 'REFRESH_LOGIN_STATE',
  SET_REFRESH_INTERVAL: 'SET_REFRESH_INTERVAL',
  CLEAR_REFRESH_INTERVAL: 'CLEAR_REFRESH_INTERVAL'
}
